CREATE TABLE FOURNISSEUR (
    ID INT PRIMARY KEY,
    NOM VARCHAR(100) NOT NULL
);

CREATE TABLE ARTICLE (
    ID INT PRIMARY KEY,
    REF VARCHAR(20) NOT NULL,
    DESIGNATION VARCHAR(100) NOT NULL, 
    PRIX DECIMAL(10,2) NOT NULL,
    ID_FOU INT NOT NULL,
    FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

CREATE TABLE BON (
    ID INT PRIMARY KEY,
    NUMERO VARCHAR(20) NOT NULL,
    DATE_CMDE DATE NOT NULL,
    DELAI INT,
    ID_FOU INT NOT NULL,
    FOREIGN KEY (ID_FOU) REFERENCES FOURNISSEUR(ID)
);

CREATE TABLE COMPO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    QTE INT NOT NULL,
    ID_ART INT NOT NULL,
    ID_BON INT NOT NULL,
    FOREIGN KEY (ID_ART) REFERENCES ARTICLE(ID),
    FOREIGN KEY (ID_BON) REFERENCES BON(ID)
);